# Project Name
# GENERATE TARGET

# Sources
# GENERATE CPP
HeavyContext.cpp \
HvHeavy.cpp \

# GENERATE C

# Library Locations
LIBDAISY_DIR = ../../libdaisy

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
