# Project Name
TARGET = pod_test

# Sources
CPP_SOURCES = pod_test.cpp \
Heavy_pod_test.cpp \
HeavyContext.cpp \
HvHeavy.cpp \

C_SOURCES = HvLightPipe.c \
HvSignalVar.c \
HvMessagePool.c \
HvControlSystem.c \
HvTable.c \
HvControlCast.c \
HvControlSlice.c \
HvUtils.c \
HvMessage.c \
HvControlVar.c \
HvSignalPhasor.c \
HvControlBinop.c \
HvMessageQueue.c \
HvControlDelay.c \


# Library Locations
LIBDAISY_DIR = ../../libdaisy

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
