# Project Name
TARGET = template

# Sources
CPP_SOURCES =  template.cpp \
HeavyContext.cpp \
Heavy_saw_test.cpp \
HvHeavy.cpp \

C_SOURCES = HvControlBinop.c \
HvControlCast.c \
HvControlVar.c \
HvLightPipe.c \
HvMessage.c \
HvMessagePool.c \
HvMessageQueue.c \
HvSignalPhasor.c \
HvSignalVar.c \
HvTable.c \
HvUtils.c \

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
